/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGraf;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author erico
 */
public class IFControlDB extends javax.swing.JPanel {

    CardLayout layout;
    final JPanel panelneutro;
    final IFSubConfigurarUsDB subConfigurarUsDB;
    final IFSubBackup subBackup;
    final IFSubAdicionar subadicionar;
    final IFSubAtualizar subAtualizar;
    /**
     * Creates new form IFControlDB
     */
    public IFControlDB() {
        initComponents();
        panelneutro = new JPanel();
        subConfigurarUsDB= new IFSubConfigurarUsDB();
        subBackup= new IFSubBackup();
        subadicionar= new IFSubAdicionar();
        subAtualizar=new IFSubAtualizar();
        subConfigurarUsDB.setVisible(true);
        pnOpcional.add(panelneutro,"panelNeutro");
        pnOpcional.add(subConfigurarUsDB,"Configuracao");
        pnOpcional.add(subBackup,"Backup");
        pnOpcional.add(subadicionar,"Adicionar");
        pnOpcional.add(subAtualizar,"Atualizar");
        layout= (CardLayout)(pnOpcional.getLayout());  
        layout.show(pnOpcional,"panelNeutro"); 
        
        
   
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lb_titulo = new javax.swing.JLabel();
        pnOpcoes = new javax.swing.JPanel();
        btAtualizar = new javax.swing.JButton();
        btAdicionar = new javax.swing.JButton();
        btConfigurar = new javax.swing.JButton();
        btBackup = new javax.swing.JButton();
        pnOpcional = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("jMenu5");

        jMenu6.setText("File");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar3.add(jMenu7);

        jMenu8.setText("File");
        jMenuBar4.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar4.add(jMenu9);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(180, 180, 180));

        lb_titulo.setBackground(new java.awt.Color(0, 102, 153));
        lb_titulo.setFont(new java.awt.Font("Catriel", 1, 14)); // NOI18N
        lb_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lb_titulo.setText("Aplicativo de Controle do Database de Mercado de Capitais");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addComponent(lb_titulo)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnOpcoes.setLayout(new java.awt.GridLayout(1, 0));

        btAtualizar.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        btAtualizar.setForeground(java.awt.Color.darkGray);
        btAtualizar.setText("Atualizar");
        btAtualizar.setOpaque(true);
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });
        pnOpcoes.add(btAtualizar);

        btAdicionar.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        btAdicionar.setForeground(java.awt.Color.darkGray);
        btAdicionar.setText("Adicionar");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });
        pnOpcoes.add(btAdicionar);

        btConfigurar.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        btConfigurar.setForeground(java.awt.Color.darkGray);
        btConfigurar.setText("Configurar");
        btConfigurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfigurarActionPerformed(evt);
            }
        });
        pnOpcoes.add(btConfigurar);

        btBackup.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        btBackup.setForeground(java.awt.Color.black);
        btBackup.setText("Backup");
        btBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackupActionPerformed(evt);
            }
        });
        pnOpcoes.add(btBackup);

        pnOpcional.setBackground(java.awt.Color.white);
        pnOpcional.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnOpcional.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnOpcoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnOpcional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnOpcional, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                .addContainerGap())
        );

        jProgressBar1.setIndeterminate(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

      
    
    private void btConfigurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfigurarActionPerformed
        // TODO add your handling code here:
    layout.show(pnOpcional,"Configuracao");
     
    }//GEN-LAST:event_btConfigurarActionPerformed

    private void btBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackupActionPerformed
        // TODO add your handling code here:
        
        layout.show(pnOpcional,"Backup"); 
    }//GEN-LAST:event_btBackupActionPerformed

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        // TODO add your handling code here:
        layout.show(pnOpcional,"Adicionar");
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        layout.show(pnOpcional, "Atualizar");
    }//GEN-LAST:event_btAtualizarActionPerformed

   protected static void lockGUI(){
       btAdicionar.setEnabled(false);
       btAtualizar.setEnabled(false);
       btBackup.setEnabled(false);
       btConfigurar.setEnabled(false);
   } 
   protected static void freeGUI(){
       btAdicionar.setEnabled(true);
       btAtualizar.setEnabled(true);
       btBackup.setEnabled(true);
       btConfigurar.setEnabled(true);
   }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton btAdicionar;
    private static javax.swing.JButton btAtualizar;
    private static javax.swing.JButton btBackup;
    private static javax.swing.JButton btConfigurar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JPanel pnOpcional;
    private javax.swing.JPanel pnOpcoes;
    // End of variables declaration//GEN-END:variables
}
