/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGraf;

import ConexaoBD.UserDB;
import Dados.ConfiguracoesIniciais;
import Dados.Diretorios;
import Diagramas.Facede;
import Diagramas.FacedeHighlander;
import Erros.Erro;
import Erros.IFSimple;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;


/**
 *
 * @author erico
 */
public class IFSubConfigurarUsDB extends javax.swing.JPanel implements lockGUI{

    /**
     * Creates new form Configurar
     */
    public IFSubConfigurarUsDB() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        tf_User = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_Hostname = new javax.swing.JTextField();
        tf_Port = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pf_Password = new javax.swing.JPasswordField();
        bt_Avancar = new javax.swing.JButton();
        lbtitle1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lbtitle2 = new javax.swing.JLabel();
        lbNomedb = new javax.swing.JLabel();
        btCriar = new javax.swing.JButton();
        lbComentario1 = new javax.swing.JLabel();
        lbComentario2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel2.setText("UserName :");

        tf_User.setText("root");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel3.setText("Hostname :");

        tf_Hostname.setText("127.0.0.1");

        tf_Port.setText("3306");

        jLabel5.setText("Port :");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel4.setText("Password  :");

        bt_Avancar.setText("Salvar Alterações");
        bt_Avancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_AvancarActionPerformed(evt);
            }
        });

        lbtitle1.setBackground(new java.awt.Color(153, 153, 153));
        lbtitle1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lbtitle1.setForeground(java.awt.Color.gray);
        lbtitle1.setText(" Configurações do usuário para conexão no MySQL");

        lbtitle2.setBackground(new java.awt.Color(153, 153, 153));
        lbtitle2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lbtitle2.setForeground(java.awt.Color.gray);
        lbtitle2.setText("Criar um novo database ");

        lbNomedb.setText("Cria um novo database . Substitui o database anterior e criando um backup  dele .");

        btCriar.setText("Criar");
        btCriar.setDoubleBuffered(true);
        btCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCriarActionPerformed(evt);
            }
        });

        lbComentario1.setForeground(java.awt.Color.red);
        lbComentario1.setText("...");

        lbComentario2.setForeground(java.awt.Color.red);
        lbComentario2.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbComentario2)
                    .addComponent(btCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNomedb))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbtitle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbtitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(162, 162, 162))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(lbComentario1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_User, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(tf_Hostname, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tf_Port, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(pf_Password, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_Avancar)
                        .addContainerGap(50, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2))
                        .addGap(12, 12, 12))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {pf_Password, tf_User});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btCriar, bt_Avancar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbtitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pf_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_Hostname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tf_Port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_Avancar))
                .addGap(14, 14, 14)
                .addComponent(lbComentario1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbtitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNomedb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCriar)
                .addGap(18, 18, 18)
                .addComponent(lbComentario2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_AvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_AvancarActionPerformed
        try{
             lbComentario1.setText("...");
             lbComentario2.setText("...");
            PrintWriter pw;
            pw =new PrintWriter(new FileWriter(Diretorios.path_datafiles_config()+"UserDB.txt"));
            pw.println("$Username$"+tf_User.getText()+"$Username$");
            pw.println("$Hostname$"+tf_Hostname.getText()+"$Hostname$");
            pw.println("$Port$"+tf_Port.getText()+"$Port$");
            pw.println("$Pass$"+String.valueOf(pf_Password.getPassword())+"$Pass$");
            pw.close();
        }catch(IOException e){return;/*nunca vai acontecer*/}
         lbComentario1.setText("Dados salvos ");
    }//GEN-LAST:event_bt_AvancarActionPerformed

    private void btCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCriarActionPerformed
       
        Criar create= new Criar();
        Thread thread = new Thread(create);
        thread.start();
        
    }//GEN-LAST:event_btCriarActionPerformed

    /*POG , porcausa do erro da Swing*/ 
    @Override
    public void lockGUI(){
        tf_User.setEnabled(false);
        tf_Hostname.setEnabled(false);
        tf_Port.setEnabled(false);
        btCriar.setEnabled(false);
        bt_Avancar.setEnabled(false);
        pf_Password.setEnabled(false);
        IFControlDB.lockGUI();
    }
    @Override
    public void freeGUI(){
        tf_User.setEnabled(true);
        tf_Hostname.setEnabled(true);
        tf_Port.setEnabled(true);
        btCriar.setEnabled(true);
        bt_Avancar.setEnabled(true);
         pf_Password.setEnabled(true);
        IFControlDB.freeGUI();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton btCriar;
    private javax.swing.JButton bt_Avancar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbComentario1;
    private javax.swing.JLabel lbComentario2;
    private javax.swing.JLabel lbNomedb;
    private javax.swing.JLabel lbtitle1;
    private javax.swing.JLabel lbtitle2;
    private javax.swing.JPasswordField pf_Password;
    private javax.swing.JTextField tf_Hostname;
    private javax.swing.JTextField tf_Port;
    private javax.swing.JTextField tf_User;
    // End of variables declaration//GEN-END:variables

    
     private class Criar implements Runnable{

         private Criar(){
              UserDB.getUserDB();
         }
         private void criar(){
        try {
                lockGUI();
                lbComentario1.setText("...");
                lbComentario2.setText("...");
               int resposta = ConfiguracoesIniciais.Config_BancodeDados();
                if(resposta==0)
               {
                   Facede facede =FacedeHighlander.getInstance();
                   facede.bovespaGetAllYears();
                   lbComentario2.setText("Processo Terminado !");
               }
               
        } catch (ConfiguracoesIniciais.ConfiguracoesIniciaisException ex) {
              IFSimple ifsimple= new IFSimple();
            ifsimple.setOption(Erro.OK_OPTION);
            ifsimple.setTitle("Erro: Grave");
            ifsimple.setTitulo("Ocorreu algum erro na Cofiguração inicial do Banco");
            ifsimple.setMessage("Não foi possivel configurar o database");
             Erro  err = new Erro(true, ifsimple);
                    err.setIdErroDB(19101);
                    err.setSystemPrintMessage("    ERRO "+ex.getMessage());
                    err.ComErroCypecad(false);
                    err.Execute();
        } catch (InterruptedException ex) {
              IFSimple ifsimple= new IFSimple();
            ifsimple.setOption(Erro.OK_OPTION);
            ifsimple.setTitle("Erro: Grave");
            ifsimple.setTitulo("Ocorreu algum erro na Cofiguração inicial do Banco");
            ifsimple.setMessage("Procedimento interrompido");
             Erro  err = new Erro(true, ifsimple);
                    err.setIdErroDB(19102);
                    err.setSystemPrintMessage("    ERRO "+ex.getMessage());
                     err.ComErroCypecad(false);
                    err.Execute();
        }finally
        {
            freeGUI();
        }
         
         }
         
        @Override
        public void run() {
            criar();
        }
     
         
     
     }

}
