/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGraf;

import ConexaoBD.UserDB;
import Dao.CiaDao;
import Diagramas.Facede;
import Diagramas.FacedeHighlander;
import Erros.Erro;
import entity.Cia;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;

/**
 *
 * @author erico
 */
public class IFSubAdicionar extends javax.swing.JPanel implements lockGUI{

    private static Cia cia;  
    private static UltimoEditavel ultimoeditavel;
    private final Font campoSelecionado = new Font("Ubuntu", Font.BOLD, 14);
    private final Font campoNSelecionado = new Font("Ubuntu", 0, 13);
    /**
     * Creates new form IFSubAdicionar
     */
    public IFSubAdicionar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbDescricao1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbtitle1 = new javax.swing.JLabel();
        pnPesquisa = new javax.swing.JPanel();
        lbDescricao2 = new javax.swing.JLabel();
        pnDados = new javax.swing.JPanel();
        lbEmpresa = new javax.swing.JLabel();
        tfEmpresa = new javax.swing.JTextField();
        lbCdBMF = new javax.swing.JLabel();
        tfCdBMF = new javax.swing.JTextField();
        lbCdCVM = new javax.swing.JLabel();
        tfCdCVM = new javax.swing.JTextField();
        lbCnpj = new javax.swing.JLabel();
        tfCnpj = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        btApagar = new javax.swing.JButton();
        lbResultado = new javax.swing.JLabel();
        btAdicionar = new javax.swing.JButton();

        lbDescricao1.setText("Adiciona os todos os arquivos  existentes da CVM  ( ITR ,DFP ) da Empresa  e adiciona a rotina de atualização . ");

        lbtitle1.setBackground(new java.awt.Color(153, 153, 153));
        lbtitle1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lbtitle1.setForeground(java.awt.Color.gray);
        lbtitle1.setText("Adicionar Empresa  à lista de empresas a ser baixada pela rotina da CVM .");

        pnPesquisa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisa de empresa ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), java.awt.Color.lightGray)); // NOI18N

        lbDescricao2.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        lbDescricao2.setText("Insira um ou mais dado(s) sobre a empresa que deseja adicionar :");

        pnDados.setLayout(new java.awt.GridLayout(5, 2, 60, 10));

        lbEmpresa.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lbEmpresa.setText("Nome da Empresa ( nome parcial )  :");
        pnDados.add(lbEmpresa);
        pnDados.add(tfEmpresa);

        lbCdBMF.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lbCdBMF.setText("Código BM&F :");
        pnDados.add(lbCdBMF);
        pnDados.add(tfCdBMF);

        lbCdCVM.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lbCdCVM.setText("Código CVM :");
        pnDados.add(lbCdCVM);
        pnDados.add(tfCdCVM);

        lbCnpj.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lbCnpj.setText("cnpj :");
        pnDados.add(lbCnpj);
        pnDados.add(tfCnpj);

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });
        pnDados.add(btBuscar);

        btApagar.setText("Apagar Campos");
        btApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btApagarActionPerformed(evt);
            }
        });
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });
        
        tfCdBMF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ultimoeditavel=UltimoEditavel.BMF;
                atualizaCampos();
            }
        });
        tfCdCVM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ultimoeditavel=UltimoEditavel.CVM;
                atualizaCampos();
            }
        });
        tfCnpj.addKeyListener(new java.awt.event.KeyAdapter(){
            @Override
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ultimoeditavel=UltimoEditavel.CNPJ;
                atualizaCampos();
            }
        });
        tfEmpresa.addKeyListener(new java.awt.event.KeyAdapter(){
            @Override
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ultimoeditavel=UltimoEditavel.NOME;
                atualizaCampos();
            }
        });
        
        
        
        pnDados.add(btApagar);

        lbResultado.setForeground(java.awt.Color.red);
        lbResultado.setText("...");

        javax.swing.GroupLayout pnPesquisaLayout = new javax.swing.GroupLayout(pnPesquisa);
        pnPesquisa.setLayout(pnPesquisaLayout);
        pnPesquisaLayout.setHorizontalGroup(
            pnPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPesquisaLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(pnPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbResultado)
                    .addComponent(lbDescricao2)
                    .addComponent(pnDados, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnPesquisaLayout.setVerticalGroup(
            pnPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPesquisaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbDescricao2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbResultado)
                .addContainerGap())
        );

        btAdicionar.setForeground(java.awt.Color.red);
        btAdicionar.setText("Adicionar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbtitle1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                        .addGap(162, 162, 162))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbDescricao1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pnPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jSeparator1)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lbtitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbDescricao1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btAdicionar)
                .addContainerGap())
       );
    }// </editor-fold>//GEN-END:initComponents

    private void atualizaCampos(){
        switch(ultimoeditavel){
            case CVM :
                tfCdCVM.setForeground(Color.BLACK);
                tfCdBMF.setForeground(Color.GRAY);
                tfCnpj.setForeground(Color.GRAY);
                tfEmpresa.setForeground(Color.GRAY);
                tfCdCVM.setFont(campoSelecionado);
                tfCdBMF.setFont(campoNSelecionado);
                tfCnpj.setFont(campoNSelecionado);
                tfEmpresa.setFont(campoNSelecionado);
                break;
            case BMF :
                tfCdCVM.setForeground(Color.GRAY);
                tfCdBMF.setForeground(Color.BLACK);
                tfCnpj.setForeground(Color.GRAY);
                tfEmpresa.setForeground(Color.GRAY);
                tfCdCVM.setFont(campoNSelecionado);
                tfCdBMF.setFont(campoSelecionado);
                tfCnpj.setFont(campoNSelecionado);
                tfEmpresa.setFont(campoNSelecionado);
                break;
            case CNPJ:
                tfCdCVM.setForeground(Color.GRAY);
                tfCdBMF.setForeground(Color.GRAY);
                tfCnpj.setForeground(Color.BLACK);
                tfEmpresa.setForeground(Color.GRAY);
                tfCdCVM.setFont(campoNSelecionado);
                tfCdBMF.setFont(campoNSelecionado);
                tfCnpj.setFont(campoSelecionado);
                tfEmpresa.setFont(campoNSelecionado);
                break;
            case NOME:
                tfCdCVM.setForeground(Color.GRAY);
                tfCdBMF.setForeground(Color.GRAY);
                tfCnpj.setForeground(Color.GRAY);
                tfEmpresa.setForeground(Color.BLACK);
                tfCdCVM.setFont(campoNSelecionado);
                tfCdBMF.setFont(campoNSelecionado);
                tfCnpj.setFont(campoNSelecionado);
                tfEmpresa.setFont(campoSelecionado);
                break;
        }
            
        
    }
    
    private void btAdicionarActionPerformed(ActionEvent evt) {
        Adicionar add = new Adicionar();
        Thread th= new Thread(add);
        th.start();
    }
    
    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        // TODO add your handling code here:
        UserDB.getUserDB();
        CiaDao ciaDao;
        lbResultado.setText("...");
        String cdBMF=tfCdBMF.getText();
        String cdCVM= tfCdCVM.getText();
        String cdCnpj= tfCnpj.getText();
        String cdEmpresa=tfEmpresa.getText();
        try {
                    if((cdEmpresa.isEmpty() && cdCnpj.isEmpty() && cdCVM.isEmpty() && cdBMF.isEmpty()) || ultimoeditavel==null ){
                        lbResultado.setText("Campos vazios");
                        return;
                    }
        switch(ultimoeditavel){
            case BMF:
                cia= new Cia(cdBMF);
               ciaDao= new CiaDao(cia);
               cia= ciaDao.getFirst();
                break;
            case CVM:
                cia= new Cia(Integer.parseInt(cdCVM));
               ciaDao= new CiaDao(cia);
               cia= ciaDao.getFirst();
                break;
            case CNPJ:
                cia = new Cia(Long.parseLong(cdCnpj));
                ciaDao= new CiaDao(cia);
                cia= ciaDao.getFirst();
                break;
            case NOME:
                cia= new Cia();
                cia.setDenominacaoSocial(cdEmpresa);
                ciaDao= new CiaDao(cia);
                cia= ciaDao.getFirst();
                break;
        }
            
      
           
        if(cia!=null)
        {
            tfCdBMF.setText(cia.getIdEmpresa());
            tfCdCVM.setText(cia.getCodCvm()+"");
            tfCnpj.setText(cia.getCnpj()+"");
            tfEmpresa.setText(cia.getDenominacaoSocial());
            lbResultado.setText("Empresa encontrada!");
        }
        else
        {
            lbResultado.setText("Não foi encontrado empresa para esse(s) parametro(s)!");
        }
        }catch (CiaDao.CiasException ex) {
                 Erro  err = new Erro(true, false);
                 err.setIdErroDB(17101);
                 err.setSystemPrintMessage("    ERRO "+ex.getMessage());
                 err.Execute();
        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btApagarActionPerformed
        // TODO add your handling code here:
        lbResultado.setText("...");
        tfCdBMF.setText("");
        tfCdCVM.setText("");
        tfCnpj.setText("");
        tfEmpresa.setText("");
    }//GEN-LAST:event_btApagarActionPerformed

    /*POG , porcausa do erro da Swing */
    @Override
    public void lockGUI(){
        tfCdBMF.setEnabled(false);
        tfCdCVM.setEnabled(false);
        tfCnpj.setEnabled(false);
        tfEmpresa.setEnabled(false);
        btAdicionar.setEnabled(false);
        btBuscar.setEnabled(false);
        btApagar.setEnabled(false);
        IFControlDB.lockGUI();
    }
    @Override
    public void freeGUI(){
        tfCdBMF.setEnabled(true);
        tfCdCVM.setEnabled(true);
        tfCnpj.setEnabled(true);
        tfEmpresa.setEnabled(true);
        btAdicionar.setEnabled(true);
        btBuscar.setEnabled(true);
        btApagar.setEnabled(true);
        IFControlDB.freeGUI();
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btApagar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbCdBMF;
    private javax.swing.JLabel lbCdCVM;
    private javax.swing.JLabel lbCnpj;
    private javax.swing.JLabel lbDescricao1;
    private javax.swing.JLabel lbDescricao2;
    private javax.swing.JLabel lbEmpresa;
    private javax.swing.JLabel lbResultado;
    private javax.swing.JLabel lbtitle1;
    private javax.swing.JPanel pnDados;
    private javax.swing.JPanel pnPesquisa;
    private javax.swing.JTextField tfCdBMF;
    private javax.swing.JTextField tfCdCVM;
    private javax.swing.JTextField tfCnpj;
    private javax.swing.JTextField tfEmpresa;
    // End of variables declaration//GEN-END:variables
    
    private enum UltimoEditavel {
    BMF,CVM,CNPJ,NOME;
}
    
    
    private class Adicionar implements Runnable{
         private  Adicionar(){
              UserDB.getUserDB();
         }
         private void add(){
             lockGUI();
              if(cia!=null)
              {
                  Facede facede = new FacedeHighlander().getInstance();
                  boolean retorno =facede.addCia(cia);
                  if(retorno)
                  {
                      lbResultado.setText("Empresa adicionada ");
                  }
                  else
                  {
                      lbResultado.setText("Não foi possível adicionar a empresa .");
                  }
              }
              else
              {
                  lbResultado.setText("Não foi encontrado empresa para esse(s) parametro(s)!");
              }
              freeGUI();
        }

        @Override
        public void run() {
            add();
        }
     
    }
    
}

