/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGraf;

import ConexaoBD.UserDB;
import Dados.ConfiguracoesDB;
import Dados.ConfiguracoesIniciais;
import Erros.Erro;
import Erros.IFSimple;


/**
 *
 * @author erico
 */
public class IFSubBackup extends javax.swing.JPanel {

    /**
     * Creates new form IFBackup
     */
    public IFSubBackup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbtitle1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btCriarBackup = new javax.swing.JButton();
        lbtitle2 = new javax.swing.JLabel();
        btRestaurar = new javax.swing.JButton();
        lbResposta1 = new javax.swing.JLabel();
        lbResposta2 = new javax.swing.JLabel();
        lbDescricao1 = new javax.swing.JLabel();
        lbDescricao2 = new javax.swing.JLabel();
        lbDescricao3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lbDescricao4 = new javax.swing.JLabel();

        lbtitle1.setBackground(new java.awt.Color(153, 153, 153));
        lbtitle1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lbtitle1.setForeground(java.awt.Color.gray);
        lbtitle1.setText("Criar Backup do Database");

        btCriarBackup.setText("Criar");
        btCriarBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCriarBackupActionPerformed(evt);
            }
        });

        lbtitle2.setBackground(new java.awt.Color(153, 153, 153));
        lbtitle2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lbtitle2.setForeground(java.awt.Color.gray);
        lbtitle2.setText("Restaurar Database a patir do Backup ");

        btRestaurar.setText("Restaurar");
        btRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRestaurarActionPerformed(evt);
            }
        });

        lbResposta1.setBackground(java.awt.Color.lightGray);
        lbResposta1.setForeground(java.awt.Color.red);
        lbResposta1.setText("...");

        lbResposta2.setForeground(java.awt.Color.red);
        lbResposta2.setText("...");

        lbDescricao1.setText("Cria arquivo .SQL  do database atual no diretorio de backups .");

        lbDescricao2.setText("Restaura um database a partir do arquivo .SQL de backup existente do diretorio de backup.");

        lbDescricao3.setText("Atenção : Fazer a Restauração substitui o database atual pelo desejado .");

        lbDescricao4.setText("Caso não exista arquivo de backup será feito um novo database .");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator3)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbtitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(173, 173, 173))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btRestaurar, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(btCriarBackup, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(lbResposta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lbtitle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDescricao2)
                            .addComponent(lbDescricao3)
                            .addComponent(lbDescricao4)
                            .addComponent(lbDescricao1)
                            .addComponent(lbResposta2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 109, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btCriarBackup, btRestaurar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbtitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(lbDescricao1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCriarBackup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbResposta1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbtitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbDescricao2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbDescricao3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbDescricao4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRestaurar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbResposta2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRestaurarActionPerformed
        // TODO add your handling code here:
        lbResposta1.setText("...");
        lbResposta2.setText("...");
        UserDB.getUserDB();
        try {
            ConfiguracoesIniciais.Config_BancodeDados();
        } catch (ConfiguracoesIniciais.ConfiguracoesIniciaisException ex) {
              IFSimple ifsimple= new IFSimple();
            ifsimple.setOption(Erro.OK_OPTION);
            ifsimple.setTitle("Erro: Grave");
            ifsimple.setTitulo("Ocorreu algum erro na Cofiguração inicial do Banco");
            ifsimple.setMessage("Não foi possivel configurar o database");
             Erro  err = new Erro(true, ifsimple);
                    err.setIdErroDB(18101);
                    err.setSystemPrintMessage("    ERRO "+ex.getMessage());
                    err.ComErroCypecad(false);
                    err.Execute();
        } catch (InterruptedException ex) {
              IFSimple ifsimple= new IFSimple();
            ifsimple.setOption(Erro.OK_OPTION);
            ifsimple.setTitle("Erro: Grave");
            ifsimple.setTitulo("Ocorreu algum erro na Cofiguração inicial do Banco");
            ifsimple.setMessage("Procedimento interrompido");
             Erro  err = new Erro(true, ifsimple);
                    err.setIdErroDB(18102);
                    err.setSystemPrintMessage("    ERRO "+ex.getMessage());
                     err.ComErroCypecad(false);
                    err.Execute();
        }
        lbResposta2.setText("Processo terminado !");
        
    }//GEN-LAST:event_btRestaurarActionPerformed

    private void btCriarBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCriarBackupActionPerformed
        // TODO add your handling code here:
                lbResposta1.setText("...");
                lbResposta2.setText("...");
                ConfiguracoesDB config= new ConfiguracoesDB();
                config.backupDataBase(ConfiguracoesIniciais.getNomeDatabasepadrao());
                lbResposta1.setText("backup feito!");
                
    }//GEN-LAST:event_btCriarBackupActionPerformed


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCriarBackup;
    private javax.swing.JButton btRestaurar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbDescricao1;
    private javax.swing.JLabel lbDescricao2;
    private javax.swing.JLabel lbDescricao3;
    private javax.swing.JLabel lbDescricao4;
    private javax.swing.JLabel lbResposta1;
    private javax.swing.JLabel lbResposta2;
    private javax.swing.JLabel lbtitle1;
    private javax.swing.JLabel lbtitle2;
    // End of variables declaration//GEN-END:variables
}
