/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGraf;

import ConexaoBD.UserDB;
import Diagramas.Facede;
import Diagramas.FacedeHighlander;
import java.awt.Color;


/**
 *
 * @author vitor
 */
public class IFSubAtualizar extends javax.swing.JPanel implements lockGUI{

    /**
     * Creates new form Atualizar
     */
    public IFSubAtualizar() {
        initComponents();
        initCiaText();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnAtualizacao = new javax.swing.JPanel();
        lbTesouro = new javax.swing.JLabel();
        btTesouro = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lbTBovespa = new javax.swing.JLabel();
        lbCVM = new javax.swing.JLabel();
        taResultado = new java.awt.TextArea();
        btCVM = new javax.swing.JButton();
        btBovespa = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        lbComentario = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(661, 373));

        pnAtualizacao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Download e Inserção das informações atuais existentes :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 3, 14), java.awt.Color.lightGray)); // NOI18N

        lbTesouro.setBackground(new java.awt.Color(153, 153, 153));
        lbTesouro.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lbTesouro.setForeground(java.awt.Color.gray);
        lbTesouro.setText("Títulos do Tesouro :");

        btTesouro.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        btTesouro.setForeground(java.awt.Color.gray);
        btTesouro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGraf/media_playback_start.png"))); // NOI18N
        btTesouro.setText("Atualizar ");
        btTesouro.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btTesouro.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btTesouro.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGraf/media_playback_start_1.png"))); // NOI18N
        btTesouro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTesouroActionPerformed(evt);
            }
        });

        lbTBovespa.setBackground(new java.awt.Color(153, 153, 153));
        lbTBovespa.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lbTBovespa.setForeground(java.awt.Color.gray);
        lbTBovespa.setText("Cotação da Bovespa :");

        lbCVM.setBackground(new java.awt.Color(153, 153, 153));
        lbCVM.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lbCVM.setForeground(java.awt.Color.gray);
        lbCVM.setText("Documentos da CVM :");

        taResultado.setBackground(new java.awt.Color(254, 254, 254));
        taResultado.setEditable(false);
        taResultado.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        taResultado.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                taResultadoComponentShown(evt);
            }
        });

        btCVM.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        btCVM.setForeground(java.awt.Color.gray);
        btCVM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGraf/media_playback_start.png"))); // NOI18N
        btCVM.setText(" Atualizar ");
        btCVM.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btCVM.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btCVM.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGraf/media_playback_start_1.png"))); // NOI18N
        btCVM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCVMActionPerformed(evt);
            }
        });

        btBovespa.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        btBovespa.setForeground(java.awt.Color.gray);
        btBovespa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGraf/media_playback_start.png"))); // NOI18N
        btBovespa.setText(" Atualizar ");
        btBovespa.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btBovespa.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btBovespa.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGraf/media_playback_start_1.png"))); // NOI18N
        btBovespa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBovespaActionPerformed(evt);
            }
        });

        lbComentario.setForeground(java.awt.Color.red);
        lbComentario.setText("...");

        javax.swing.GroupLayout pnAtualizacaoLayout = new javax.swing.GroupLayout(pnAtualizacao);
        pnAtualizacao.setLayout(pnAtualizacaoLayout);
        pnAtualizacaoLayout.setHorizontalGroup(
            pnAtualizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnAtualizacaoLayout.createSequentialGroup()
                .addGroup(pnAtualizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbComentario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addGroup(pnAtualizacaoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnAtualizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTesouro)
                            .addComponent(lbTBovespa)
                            .addComponent(lbCVM))
                        .addGap(390, 390, 390)
                        .addGroup(pnAtualizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btTesouro, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btBovespa, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btCVM, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );

        pnAtualizacaoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btBovespa, btCVM, btTesouro});

        pnAtualizacaoLayout.setVerticalGroup(
            pnAtualizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAtualizacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnAtualizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btTesouro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTesouro))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(pnAtualizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbTBovespa)
                    .addComponent(btBovespa))
                .addGap(19, 19, 19)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(pnAtualizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbCVM)
                    .addComponent(btCVM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbComentario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnAtualizacaoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btBovespa, btCVM, btTesouro});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(pnAtualizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pnAtualizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btTesouroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTesouroActionPerformed

       String data;
       lbComentario.setText("...");
       f.setTesouro();
       data = f.getTesouroInfo();
       taResultado.setText("Data de atualização : "+data);
       taResultado.setForeground(Color.RED);
       f.tesouroRotine();
        
       if(!data.equals(f.getTesouroInfo()))
           taResultado.setText(f.getTesouroInfo());
       taResultado.setForeground(Color.GREEN);
       lbComentario.setText("Atualização do Tesouro Concluída .");
    }//GEN-LAST:event_btTesouroActionPerformed

    private void btCVMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCVMActionPerformed
        AtualizarCvm  atualizar = new AtualizarCvm();
        Thread th = new Thread(atualizar);
        th.start();
        
    }//GEN-LAST:event_btCVMActionPerformed

    private void btBovespaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBovespaActionPerformed
        AtualizarBmf atual = new AtualizarBmf();
        Thread th = new Thread(atual);
        th.start();
    }//GEN-LAST:event_btBovespaActionPerformed

    private void taResultadoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_taResultadoComponentShown
        
       
    }//GEN-LAST:event_taResultadoComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBovespa;
    private javax.swing.JButton btCVM;
    private javax.swing.JButton btTesouro;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lbCVM;
    private javax.swing.JLabel lbComentario;
    private javax.swing.JLabel lbTBovespa;
    private javax.swing.JLabel lbTesouro;
    private javax.swing.JPanel pnAtualizacao;
    private java.awt.TextArea taResultado;
    // End of variables declaration//GEN-END:variables

    private final Facede f = FacedeHighlander.getInstance();
    
    private void initCiaText(){
        
        int i = 0;
        String temp[] , text = "";
        temp = f.getCias();
        while( i < temp.length){    
            text += "    " + temp[i] + "\n";
        taResultado.setText(text);
            i++;
        }
        taResultado.setEditable(false);
    }
    
    /*POG , por causa do erro da Swing .*/
    @Override
    public void lockGUI(){
        btBovespa.setEnabled(false);
        btCVM.setEnabled(false);
        btTesouro.setEnabled(false);
        IFControlDB.lockGUI();
    }
    @Override
    public void freeGUI(){
        btBovespa.setEnabled(true);
        btCVM.setEnabled(true);
        btTesouro.setEnabled(true);
        IFControlDB.freeGUI();
    }
    
    private class AtualizarBmf implements Runnable{

         private AtualizarBmf(){
              UserDB.getUserDB();
         }
         private void atualiza(){
                   lockGUI();
                   lbComentario.setText("...");
                   taResultado.setText("Preparando Cotação ...");
                   taResultado.setForeground(Color.RED);
                   f.bovespaRotine();
                   lbComentario.setText("Atualização da Cotacão da Bovespa Concluída .");
                   taResultado.setText("Cotação Atualizada");
                   taResultado.setForeground(Color.GREEN);
                   freeGUI();
         }
         
        @Override
        public void run() {
            atualiza();
        }
    
    }
    
     private class AtualizarCvm implements Runnable{

         private AtualizarCvm(){
              UserDB.getUserDB();
         }
         private void atualiza(){
                   lockGUI();
                   lbComentario.setText("...");
                   taResultado.setText("Preparando ITR/DFP ...");
                   taResultado.setForeground(Color.RED);
                   f.atualizaCias();
                   lbComentario.setText("Atualização da Cotacão da CVM Concluída .");
                   lbComentario.repaint();
                   taResultado.setText("Informações Atualizada");
                   taResultado.setForeground(Color.GREEN);
                   freeGUI();
         }
         
        @Override
        public void run() {
            atualiza();
        }
         
     
     }
    
    
    
}
